# Generated by Django 2.1.2 on 2019-02-22 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AcceptedUsers',
            fields=[
                ('employee_id', models.IntegerField(primary_key=True, serialize=False)),
                ('empusername', models.CharField(max_length=30)),
                ('emppassword', models.CharField(max_length=20)),
                ('address', models.TextField()),
                ('email', models.EmailField(max_length=30)),
                ('contact', models.IntegerField()),
                ('dob', models.DateField()),
                ('comp_name', models.CharField(max_length=30)),
                ('status', models.CharField(default=False, max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=20)),
                ('type', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='ApprovalUsers',
            fields=[
                ('employee_id', models.IntegerField(primary_key=True, serialize=False)),
                ('empusername', models.CharField(max_length=30)),
                ('emppassword', models.CharField(max_length=20)),
                ('address', models.TextField()),
                ('email', models.EmailField(max_length=30)),
                ('contact', models.IntegerField()),
                ('dob', models.DateField(default=False)),
                ('company_name', models.CharField(max_length=30)),
                ('status', models.CharField(default=False, max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Celebrations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('address', models.TextField()),
                ('contact_no', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('dob', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Events',
            fields=[
                ('username', models.CharField(max_length=30)),
                ('startdate', models.DateField()),
                ('enddate', models.DateField()),
                ('description', models.TextField(max_length=100)),
                ('contact_No', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Matrimonial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bride_or_bridegromname', models.CharField(max_length=30)),
                ('gender', models.CharField(choices=[('MALE', 'male'), ('FEMALE', 'female')], max_length=5)),
                ('userdate_of_birth', models.DateField()),
                ('description', models.TextField()),
                ('contact_no', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30)),
                ('property_type', models.CharField(choices=[('--select--', '--select--'), ('SALE', 'sale'), ('RENT', 'rent')], max_length=10)),
                ('property_title', models.CharField(max_length=30)),
                ('area_in_size', models.IntegerField()),
                ('prise', models.DecimalField(decimal_places=2, max_digits=10)),
                ('address', models.TextField()),
                ('contact_no', models.IntegerField()),
                ('email_id', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Reference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30)),
                ('job_title', models.CharField(max_length=30)),
                ('description', models.TextField()),
                ('last_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='RejectedUser',
            fields=[
                ('employee_id', models.IntegerField(primary_key=True, serialize=False)),
                ('empusername', models.CharField(max_length=30)),
                ('emp_password', models.CharField(max_length=20)),
                ('address', models.TextField()),
                ('email', models.EmailField(max_length=30)),
                ('contact', models.IntegerField()),
                ('dob', models.DateField()),
                ('company_name', models.CharField(max_length=30)),
                ('status', models.CharField(default=False, max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='ShareMarket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30)),
                ('company_name', models.CharField(max_length=50)),
                ('share_value', models.IntegerField()),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Technical',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30)),
                ('technology', models.CharField(default=False, max_length=30)),
                ('description', models.TextField(max_length=30)),
                ('contact_no', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Thoughts',
            fields=[
                ('username', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=100)),
                ('contact_No', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Travel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30)),
                ('travel_date', models.DateField()),
                ('location', models.TextField()),
                ('description', models.TextField()),
                ('contact_no', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='WorkExperience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30)),
                ('technology', models.CharField(max_length=30)),
                ('workExperience', models.CharField(max_length=10)),
                ('description', models.CharField(max_length=30)),
                ('contact_no', models.IntegerField()),
            ],
        ),
    ]
