# Generated by Django 2.1.2 on 2019-02-23 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cewn', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='acceptedusers',
            old_name='emppassword',
            new_name='password',
        ),
        migrations.RenameField(
            model_name='acceptedusers',
            old_name='empusername',
            new_name='username',
        ),
        migrations.RenameField(
            model_name='approvalusers',
            old_name='emppassword',
            new_name='password',
        ),
        migrations.RenameField(
            model_name='approvalusers',
            old_name='empusername',
            new_name='username',
        ),
        migrations.RenameField(
            model_name='rejecteduser',
            old_name='emp_password',
            new_name='password',
        ),
        migrations.RenameField(
            model_name='rejecteduser',
            old_name='empusername',
            new_name='username',
        ),
    ]
