# Generated by Django 2.1.2 on 2019-02-23 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cewn', '0002_auto_20190223_1743'),
    ]

    operations = [
        migrations.RenameField(
            model_name='acceptedusers',
            old_name='comp_name',
            new_name='company_name',
        ),
        migrations.RenameField(
            model_name='acceptedusers',
            old_name='contact',
            new_name='contact_no',
        ),
        migrations.RenameField(
            model_name='acceptedusers',
            old_name='dob',
            new_name='date_of_birth',
        ),
        migrations.RenameField(
            model_name='acceptedusers',
            old_name='email',
            new_name='email_id',
        ),
        migrations.RenameField(
            model_name='approvalusers',
            old_name='contact',
            new_name='contact_no',
        ),
        migrations.RenameField(
            model_name='approvalusers',
            old_name='dob',
            new_name='date_of_birth',
        ),
        migrations.RenameField(
            model_name='approvalusers',
            old_name='email',
            new_name='email_id',
        ),
        migrations.RenameField(
            model_name='celebrations',
            old_name='dob',
            new_name='date_of_birth',
        ),
        migrations.RenameField(
            model_name='celebrations',
            old_name='email',
            new_name='email_id',
        ),
        migrations.RenameField(
            model_name='property',
            old_name='prise',
            new_name='price',
        ),
        migrations.RenameField(
            model_name='rejecteduser',
            old_name='contact',
            new_name='contact_no',
        ),
        migrations.RenameField(
            model_name='rejecteduser',
            old_name='dob',
            new_name='date_of_birth',
        ),
        migrations.RenameField(
            model_name='rejecteduser',
            old_name='email',
            new_name='email_id',
        ),
    ]
