# Generated by Django 2.1.2 on 2019-02-24 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cewn', '0003_auto_20190223_1750'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acceptedusers',
            name='employee_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='approvalusers',
            name='employee_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='rejecteduser',
            name='employee_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
