# Generated by Django 2.1.2 on 2019-02-24 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cewn', '0004_auto_20190224_2249'),
    ]

    operations = [
        migrations.RenameField(
            model_name='events',
            old_name='contact_No',
            new_name='contact_no',
        ),
        migrations.RenameField(
            model_name='thoughts',
            old_name='contact_No',
            new_name='contact_no',
        ),
    ]
