# Generated by Django 2.1.2 on 2019-02-24 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cewn', '0005_auto_20190224_2300'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='acceptedusers',
            name='date_of_birth',
        ),
        migrations.RemoveField(
            model_name='rejecteduser',
            name='date_of_birth',
        ),
    ]
