# Generated by Django 2.1.2 on 2019-02-25 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cewn', '0006_auto_20190225_0042'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='technical',
            name='technology',
        ),
    ]
