# Generated by Django 2.1.2 on 2019-02-25 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cewn', '0007_remove_technical_technology'),
    ]

    operations = [
        migrations.AddField(
            model_name='technical',
            name='technology',
            field=models.CharField(default=False, max_length=30),
        ),
    ]
