# Generated by Django 2.1.2 on 2019-02-25 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cewn', '0008_technical_technology'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workexperience',
            old_name='technology',
            new_name='usertechnology',
        ),
    ]
