# Generated by Django 2.1.2 on 2019-02-25 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cewn', '0009_auto_20190225_1952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='technical',
            name='technology',
            field=models.CharField(max_length=30),
        ),
    ]
