# Generated by Django 2.1.2 on 2019-02-25 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cewn', '0010_auto_20190225_1954'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workexperience',
            old_name='usertechnology',
            new_name='technology',
        ),
    ]
