# Generated by Django 2.1.2 on 2019-02-25 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cewn', '0011_auto_20190225_1955'),
    ]

    operations = [
        migrations.RenameField(
            model_name='matrimonial',
            old_name='userdate_of_birth',
            new_name='date_of_birth',
        ),
    ]
